name: CI-CD # Give your workflow a name

#on: push # Run the workflow for each push event (i.e commit)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-js:
    name: Build Js/Css
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        # Build JS
      - name: Yarn Build
        run: |
          yarn install
          yarn prod
          cat public/mix-manifest.json # See asset versions in log
      - name: Upload build files
        uses: actions/upload-artifact@v1
        with:
          name: assets
          path: public

  test-php:
      name: Test/Lint PHP
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
        # Test and Lint PHP code
    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: 7.3 # Use your PHP version
        extensions: mbstring, bcmath # Setup any required extensions for tests
    - name: Composer install
      run: composer install
    - name: Run Tests
      run: ./vendor/bin/phpunit
        