name: CI-CD

on:
  push:
    branches: main

jobs:
  test-php:
    name: Test/Lint PHP
    runs-on: ubuntu-latest 
    needs: build-js
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.3 # Use your PHP version
          extensions: mbstring, bcmath # Setup any required extensions for tests
      - name: Composer install
        run: composer install
      - name: Run Tests
        run: ./vendor/bin/phpunit
