name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
  
    steps:
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          username: root          
          host: "159.89.171.253"
          password: "Raghav2020@Test"
          script: 'cd /var/www/html/ && ./deployer.sh' 
