  on: push
  name: Publish Website
  jobs:
    FTP-Deploy-Action:
      name : FTP-Deploy-Action
      runs-on : ubuntu-latest
      steps:

      -users : actions/checkout@v2.1.0
        with:
        fetch-depth: 2
      -name : FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: 159.89.171.253
        ftp-username: root
        ftp-password: Raghav2020@Test

