name: Laravel
on:
  push:
    branches: [ main ]
jobs:
  web-deploy:
    name:  Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: 159.89.171.253
        username: root
        password: Raghav2020@Test
        protocol: ftps
        port: 22 
