name: CD
 
on:
  push:
    branches: [ main ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    - name: Deploy to main
      uses: appleboy/ssh-action@master
      with:
        username: root
        host: 159.89.171.253
        password: Raghav2020@Test
        script: 'cd /var/www/html && ./server_deploy.sh'