name: CD
 
on:
  push:
    branches: [ main ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: 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
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run main
    - name: Commit built assets
      run: |
        git config --local user.email "varun@mindrops.com"
        git config --local user.name "varun dhiman"
        git checkout -B deploy
        git add -f public/
        git commit -m "Build front-end assets"
        git push -f origin deploy
    - name: Deploy to main
      uses: appleboy/ssh-action@master
      with:
        username: root
        host: 159.89.171.253
        password: Raghav2020@Test
        script: 'cd /var/www/html && ./server_deploy.sh'